Updates for Media features and Subresource Integrity
MicrosoftEdge/Status pull request #534
Opened 2017-08-02 23:37 UTC by kypflug

* Subresource Integrity now available behind the Service Worker flag (16257+)
* Screen Capture API is In Development
* Added new backlog features for tracking: Media Capture from Canvas, Media Capture from HTML Media Element, and Audio Output Devices API

2017-08-03 00:01 UTC, alrra requested changes

2017-08-03 00:01 UTC, alrra commented on status.json
> +    "standardStatus": "Editor's Draft",
Needs to be `draft`, not `Draft`.

2017-08-03 00:01 UTC, alrra commented on status.json
> +      "ie": "16257",
Needs to be either `iePrefixed` or `ieUnprefixed`.

2017-08-03 00:02 UTC, alrra commented
@kypflug Build [is failing](https://travis-ci.org/MicrosoftEdge/Status/builds/260416830#L468). Left some inline comments that need to be addressed.

2017-08-03 00:12 UTC, alrra commented
Merged with some modifications (i.e. integrated the fixes in the correct commits, and changed the commit messages a bit).

2017-08-03 00:12 UTC, closed without merging

2017-08-14 00:55 UTC, mkurz commented
The uservoice ticket for subresource integrity hasn't been update yet:
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6263699-subresource-integrity

2017-08-14 05:26 UTC, molant commented
@dstorey can you update it?